on:
  push:
    branches:
      - main

name: Deploy Cloudflare Workers
jobs:
  builddeploy:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        root-project-path: [./]
    steps:
    - uses: actions/checkout@v4
    - name: setup ubuntu
      run: |
        sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ${{ matrix.root-project-path }}
      run: yarn install
    - name: deploy to cloudflare workers
      uses: cloudflare/wrangler-action@v3
      with:
        workingDirectory: ${{ matrix.root-project-path }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        secrets: |
          GOOGLE_API_OAUTH2_CLIENT_ID
          GOOGLE_API_OAUTH2_CLIENT_SECRET
          GOOGLE_API_KEY
          DEBUG_PRIVATE_GOOGLE_TASK_REFRESH_TOKEN
      env:
        GOOGLE_API_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_API_OAUTH2_CLIENT_ID }}
        GOOGLE_API_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_API_OAUTH2_CLIENT_SECRET }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DEBUG_PRIVATE_GOOGLE_TASK_REFRESH_TOKEN: ${{ secrets.DEBUG_PRIVATE_GOOGLE_TASK_REFRESH_TOKEN }}